## Listing 5.1 Instantiating a small convnet

In [3]:
from tensorflow.keras import layers
from tensorflow.keras import models


model = models.Sequential()

model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

In [4]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 13, 13, 32)       0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
Total params: 55,744
Trainable params: 55,744
Non-trai

# Listing 5.2 Adding a classifier on top of the **convnet**

In [5]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [6]:
3*3*64

576

In [7]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 13, 13, 32)       0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
 flatten (Flatten)           (None, 576)              

# Listing 5.3 Training the convnet on MNIST images

In [8]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [9]:
print(train_images.shape, train_labels.shape)

(60000, 28, 28) (60000,)


In [10]:
print(test_images.shape, test_labels.shape)

(10000, 28, 28) (10000,)


In [11]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [12]:
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5, batch_size=64)

Epoch 1/5
938/938 [==============================] - 27s 28ms/step - loss: 0.1798 - accuracy: 0.9439
Epoch 2/5
938/938 [==============================] - 26s 28ms/step - loss: 0.0485 - accuracy: 0.9853
Epoch 3/5
938/938 [==============================] - 26s 28ms/step - loss: 0.0328 - accuracy: 0.9898
Epoch 4/5
938/938 [==============================] - 26s 27ms/step - loss: 0.0249 - accuracy: 0.9923
Epoch 5/5
938/938 [==============================] - 26s 28ms/step - loss: 0.0200 - accuracy: 0.9941


In [13]:
import numpy as np
from sklearn.metrics import precision_score, recall_score

# Get the predicted labels from the model
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)

# Convert the one-hot encoded test labels back to categorical labels
true_labels = np.argmax(test_labels, axis=1)

# Calculate precision and recall
precision = precision_score(true_labels, predicted_labels, average='weighted')
recall = recall_score(true_labels, predicted_labels, average='weighted')

print("Precision:", precision)
print("Recall:", recall)


313/313 [==============================] - 2s 5ms/step
Precision: 0.9906597077472987
Recall: 0.9906


# Testing

In [14]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)
print(test_loss)

313/313 [==============================] - 2s 5ms/step - loss: 0.0307 - accuracy: 0.9906
0.9905999898910522
0.030699938535690308


In [16]:
import numpy as np
from sklearn.metrics import f1_score, confusion_matrix

In [19]:
# Calculate F1 score
f1 = f1_score(true_labels, predicted_labels, average='weighted')

print("F1 Score:", f1)
print("----------------------------------")
# Generate confusion matrix
confusion_mtx = confusion_matrix(true_labels, predicted_labels)

print("Confusion Matrix:")

print(confusion_mtx)

F1 Score: 0.9906010337067462
----------------------------------
Confusion Matrix:
[[ 976    1    1    0    0    0    1    1    0    0]
 [   0 1133    2    0    0    0    0    0    0    0]
 [   0    0 1028    0    0    0    0    4    0    0]
 [   0    0    1 1001    0    5    0    3    0    0]
 [   0    0    0    0  968    0    3    1    7    3]
 [   1    0    0    5    0  882    1    0    3    0]
 [   2    2    0    0    0    2  949    0    3    0]
 [   0    1    5    0    0    0    0 1019    2    1]
 [   1    0    1    1    0    0    0    1  968    2]
 [   0    2    0    0    1    6    0    7   11  982]]


# prediction for output

In [14]:
p = model.predict(test_images )
p

313/313 [==============================] - 2s 5ms/step


array([[1.78680367e-20, 1.49757545e-06, 5.96221798e-05, ...,
        9.99780595e-01, 3.14197388e-12, 1.57187824e-04],
       [6.66074129e-09, 6.74596686e-06, 9.99217272e-01, ...,
        7.93974832e-05, 1.15147690e-04, 5.81783888e-06],
       [2.82936841e-10, 9.99823034e-01, 6.36398525e-08, ...,
        1.69010877e-06, 1.75043504e-04, 3.27200844e-08],
       ...,
       [1.60805386e-04, 3.04156106e-06, 5.32270263e-08, ...,
        2.09948979e-07, 9.44430738e-08, 3.01132823e-04],
       [1.00324814e-05, 9.68105041e-11, 1.15280754e-08, ...,
        1.36977955e-11, 1.60464295e-03, 6.25548011e-04],
       [1.44166040e-06, 1.23260881e-11, 3.40796279e-04, ...,
        2.02956494e-13, 2.80863751e-05, 2.41295222e-12]], dtype=float32)

In [15]:
p[0]

array([1.7868037e-20, 1.4975755e-06, 5.9622180e-05, 4.9753188e-09,
       1.0038026e-06, 1.3403420e-15, 2.6103628e-16, 9.9978060e-01,
       3.1419739e-12, 1.5718782e-04], dtype=float32)

In [16]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)